package format

import (
	"regexp"
	"strings"
)

var reEmoji = regexp.MustCompile(`:([a-zA-Z0-9_+-]+):`)

// ReplaceEmoji replaces :emoji_name: with Unicode emoji characters.
func ReplaceEmoji(text string) string {
	return reEmoji.ReplaceAllStringFunc(text, func(match string) string {
		name := strings.Trim(match, ":")
		if emoji, ok := emojiMap[name]; ok {
			return emoji
		}
		return match // keep original if not found (could be custom workspace emoji)
	})
}

// emojiMap maps Slack emoji short codes to Unicode emoji.
// Covers the most commonly used emoji in Slack.
var emojiMap = map[string]string{
	// Smileys & People
	"smile":                        "😄",
	"smiley":                       "😃",
	"grinning":                     "😀",
	"grin":                         "😁",
	"laughing":                     "😆",
	"satisfied":                    "😆",
	"sweat_smile":                  "😅",
	"rofl":                         "🤣",
	"joy":                          "😂",
	"slightly_smiling_face":        "🙂",
	"upside_down_face":             "🙃",
	"wink":                         "😉",
	"blush":                        "😊",
	"innocent":                     "😇",
	"heart_eyes":                   "😍",
	"kissing_heart":                "😘",
	"kissing":                      "😗",
	"relaxed":                      "☺️",
	"kissing_closed_eyes":          "😚",
	"kissing_smiling_eyes":         "😙",
	"yum":                          "😋",
	"stuck_out_tongue":             "😛",
	"stuck_out_tongue_winking_eye": "😜",
	"stuck_out_tongue_closed_eyes": "😝",
	"sunglasses":                   "😎",
	"hugging_face":                 "🤗",
	"thinking_face":                "🤔",
	"thinking":                     "🤔",
	"face_with_raised_eyebrow":     "🤨",
	"neutral_face":                 "😐",
	"expressionless":               "😑",
	"no_mouth":                     "😶",
	"rolling_eyes":                 "🙄",
	"smirk":                        "😏",
	"persevere":                    "😣",
	"disappointed":                 "😞",
	"confused":                     "😕",
	"worried":                      "😟",
	"angry":                        "😠",
	"rage":                         "😡",
	"cry":                          "😢",
	"sob":                          "😭",
	"scream":                       "😱",
	"fearful":                      "😨",
	"cold_sweat":                   "😰",
	"disappointed_relieved":        "😥",
	"sweat":                        "😓",
	"sleeping":                     "😴",
	"sleepy":                       "😪",
	"dizzy_face":                   "😵",
	"zipper_mouth_face":            "🤐",
	"mask":                         "😷",
	"face_with_thermometer":        "🤒",
	"nerd_face":                    "🤓",
	"skull":                        "💀",
	"ghost":                        "👻",
	"alien":                        "👽",
	"robot_face":                   "🤖",
	"poop":                         "💩",
	"hankey":                       "💩",
	"clown_face":                   "🤡",
	"see_no_evil":                  "🙈",
	"hear_no_evil":                 "🙉",
	"speak_no_evil":                "🙊",
	"wave":                         "👋",
	"raised_back_of_hand":          "🤚",
	"raised_hand":                  "✋",
	"hand":                         "✋",
	"vulcan_salute":                "🖖",
	"ok_hand":                      "👌",
	"v":                            "✌️",
	"crossed_fingers":              "🤞",
	"metal":                        "🤘",
	"call_me_hand":                 "🤙",
	"point_left":                   "👈",
	"point_right":                  "👉",
	"point_up":                     "👆",
	"point_up_2":                   "☝️",
	"point_down":                   "👇",
	"thumbsup":                     "👍",
	"+1":                           "👍",
	"thumbsdown":                   "👎",
	"-1":                           "👎",
	"fist":                         "✊",
	"facepunch":                    "👊",
	"punch":                        "👊",
	"fist_left":                    "🤛",
	"fist_right":                   "🤜",
	"clap":                         "👏",
	"raised_hands":                 "🙌",
	"open_hands":                   "👐",
	"handshake":                    "🤝",
	"pray":                         "🙏",
	"muscle":                       "💪",
	"eyes":                         "👀",
	"eye":                          "👁️",
	"brain":                        "🧠",

	// Hearts & Emotions
	"heart":           "❤️",
	"red_heart":       "❤️",
	"orange_heart":    "🧡",
	"yellow_heart":    "💛",
	"green_heart":     "💚",
	"blue_heart":      "💙",
	"purple_heart":    "💜",
	"black_heart":     "🖤",
	"white_heart":     "🤍",
	"broken_heart":    "💔",
	"heartbeat":       "💓",
	"heartpulse":      "💗",
	"sparkling_heart": "💖",
	"cupid":           "💘",
	"gift_heart":      "💝",
	"fire":            "🔥",
	"star":            "⭐",
	"star2":           "🌟",
	"sparkles":        "✨",
	"boom":            "💥",
	"collision":       "💥",
	"zap":             "⚡",
	"sunny":           "☀️",
	"rainbow":         "🌈",
	"100":             "💯",

	// Common Objects & Symbols
	"tada":                       "🎉",
	"confetti_ball":              "🎊",
	"balloon":                    "🎈",
	"party_popper":               "🎉",
	"gift":                       "🎁",
	"trophy":                     "🏆",
	"medal":                      "🏅",
	"crown":                      "👑",
	"gem":                        "💎",
	"moneybag":                   "💰",
	"dollar":                     "💵",
	"chart_with_upwards_trend":   "📈",
	"chart_with_downwards_trend": "📉",
	"bulb":                       "💡",
	"wrench":                     "🔧",
	"hammer":                     "🔨",
	"gear":                       "⚙️",
	"link":                       "🔗",
	"pushpin":                    "📌",
	"paperclip":                  "📎",
	"scissors":                   "✂️",
	"lock":                       "🔒",
	"unlock":                     "🔓",
	"key":                        "🔑",
	"bell":                       "🔔",
	"mega":                       "📣",
	"loudspeaker":                "📢",
	"email":                      "📧",
	"envelope":                   "✉️",
	"memo":                       "📝",
	"pencil":                     "✏️",
	"pencil2":                    "✏️",
	"book":                       "📖",
	"books":                      "📚",
	"folder":                     "📁",
	"file_folder":                "📁",
	"calendar":                   "📅",
	"clock":                      "🕐",
	"hourglass":                  "⏳",
	"phone":                      "📱",
	"computer":                   "💻",
	"desktop_computer":           "🖥️",
	"keyboard":                   "⌨️",
	"floppy_disk":                "💾",
	"cd":                         "💿",
	"camera":                     "📷",
	"mag":                        "🔍",
	"mag_right":                  "🔎",
	"microscope":                 "🔬",

	// Checkmarks & Status
	"white_check_mark":            "✅",
	"heavy_check_mark":            "✔️",
	"ballot_box_with_check":       "☑️",
	"x":                           "❌",
	"negative_squared_cross_mark": "❎",
	"heavy_plus_sign":             "➕",
	"heavy_minus_sign":            "➖",
	"exclamation":                 "❗",
	"question":                    "❓",
	"grey_exclamation":            "❕",
	"grey_question":               "❔",
	"warning":                     "⚠️",
	"no_entry":                    "⛔",
	"no_entry_sign":               "🚫",
	"stop_sign":                   "🛑",
	"construction":                "🚧",
	"red_circle":                  "🔴",
	"orange_circle":               "🟠",
	"yellow_circle":               "🟡",
	"green_circle":                "🟢",
	"blue_circle":                 "🔵",
	"white_circle":                "⚪",
	"black_circle":                "⚫",
	"large_blue_diamond":          "🔷",
	"large_orange_diamond":        "🔶",
	"small_blue_diamond":          "🔹",
	"small_orange_diamond":        "🔸",

	// Arrows
	"arrow_up":                  "⬆️",
	"arrow_down":                "⬇️",
	"arrow_left":                "⬅️",
	"arrow_right":               "➡️",
	"arrow_upper_right":         "↗️",
	"arrow_lower_right":         "↘️",
	"arrow_upper_left":          "↖️",
	"arrow_lower_left":          "↙️",
	"arrows_counterclockwise":   "🔄",
	"leftwards_arrow_with_hook": "↩️",
	"arrow_right_hook":          "↪️",

	// Food & Drink
	"coffee":     "☕",
	"tea":        "🍵",
	"beer":       "🍺",
	"beers":      "🍻",
	"wine_glass": "🍷",
	"cocktail":   "🍸",
	"pizza":      "🍕",
	"hamburger":  "🍔",
	"taco":       "🌮",
	"burrito":    "🌯",
	"popcorn":    "🍿",
	"cake":       "🎂",
	"cookie":     "🍪",
	"doughnut":   "🍩",
	"ice_cream":  "🍨",
	"apple":      "🍎",
	"banana":     "🍌",
	"watermelon": "🍉",
	"avocado":    "🥑",
	"hot_pepper": "🌶️",

	// Animals
	"dog":          "🐶",
	"cat":          "🐱",
	"mouse_face":   "🐭",
	"hamster":      "🐹",
	"rabbit":       "🐰",
	"fox_face":     "🦊",
	"bear":         "🐻",
	"panda_face":   "🐼",
	"penguin":      "🐧",
	"chicken":      "🐔",
	"bird":         "🐦",
	"frog":         "🐸",
	"monkey_face":  "🐵",
	"monkey":       "🐒",
	"unicorn_face": "🦄",
	"unicorn":      "🦄",
	"snake":        "🐍",
	"turtle":       "🐢",
	"fish":         "🐟",
	"whale":        "🐳",
	"dolphin":      "🐬",
	"octopus":      "🐙",
	"butterfly":    "🦋",
	"bug":          "🐛",
	"bee":          "🐝",

	// Nature & Weather
	"sun_with_face":        "🌞",
	"full_moon_with_face":  "🌝",
	"cloud":                "☁️",
	"rain_cloud":           "🌧️",
	"snowflake":            "❄️",
	"wind_blowing_face":    "🌬️",
	"tornado":              "🌪️",
	"ocean":                "🌊",
	"earth_americas":       "🌎",
	"earth_africa":         "🌍",
	"earth_asia":           "🌏",
	"globe_with_meridians": "🌐",
	"cherry_blossom":       "🌸",
	"rose":                 "🌹",
	"sunflower":            "🌻",
	"herb":                 "🌿",
	"seedling":             "🌱",
	"evergreen_tree":       "🌲",
	"deciduous_tree":       "🌳",
	"cactus":               "🌵",
	"mushroom":             "🍄",
	"fallen_leaf":          "🍂",
	"maple_leaf":           "🍁",
	"four_leaf_clover":     "🍀",

	// Transport & Places
	"rocket":   "🚀",
	"airplane": "✈️",
	"car":      "🚗",
	"taxi":     "🚕",
	"bus":      "🚌",
	"bike":     "🚲",
	"ship":     "🚢",
	"house":    "🏠",
	"office":   "🏢",
	"hospital": "🏥",
	"school":   "🏫",
	"tent":     "⛺",
	"fuelpump": "⛽",
	"anchor":   "⚓",

	// Slack-specific common
	"shipit":                           "🐿️",
	"troll":                            "🧌",
	"parrot":                           "🦜",
	"this":                             "👆",
	"ack":                              "👍",
	"lgtm":                             "👍",
	"shipping":                         "🚢",
	"raised_hand_with_fingers_splayed": "🖐️",
	"middle_finger":                    "🖕",
	"writing_hand":                     "✍️",
	"nail_care":                        "💅",
	"selfie":                           "🤳",
	"dancer":                           "💃",
	"man_dancing":                      "🕺",
	"running":                          "🏃",
	"walking":                          "🚶",
	"bath":                             "🛀",
	"sleeping_accommodation":           "🛌",
	"speech_balloon":                   "💬",
	"thought_balloon":                  "💭",
	"flag-us":                          "🇺🇸",
	"flag-gb":                          "🇬🇧",
	"flag-jp":                          "🇯🇵",
	"flag-kr":                          "🇰🇷",
	"flag-de":                          "🇩🇪",
	"flag-fr":                          "🇫🇷",
	"flag-es":                          "🇪🇸",
	"flag-it":                          "🇮🇹",
	"flag-br":                          "🇧🇷",
	"flag-ca":                          "🇨🇦",
	"flag-au":                          "🇦🇺",
	"flag-in":                          "🇮🇳",
}
